CREATE TABLE songs
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
artist VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
trackno TINYINT,
album VARCHAR(50),
year INT,
filename VARCHAR(200) NOT NULL,
md5sum CHAR(32) NOT NULL
);
 
